// MicroPython version info
#define MICROPY_GIT_TAG "ESP32_LoBo_v2.0.7"
#define MICROPY_GIT_HASH "abcdef3"
#define MICROPY_BUILD_DATE "2017-11-01"
#define MICROPY_VERSION_MAJOR (2)
#define MICROPY_VERSION_MINOR (0)
#define MICROPY_VERSION_MICRO (7)
#define MICROPY_VERSION_STRING "2.0.7"
